services:
  emqx:
    image: emqx:5.8.4
    restart: always
    container_name: emqx
    ports:
      - 1883:1883   # Port MQTT
      - 8083:8083   # Port SSL
      - 8883:8883   # Port WS
      - 8084:8084   # Port WSS
      - 18083:18083 # Port HTTP Server
    environment:
      EMQX_DASHBOARD__DEFAULT_PASSWORD: admin123
      EMQX_NODE__NAME: foo_emqx@127.0.0.1
    networks:
      - health_monitoring_network
  kafka:
    image: apache/kafka:3.7.2
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:9092,PLAINTEXT_EXTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LISTENER_NAME_INTERNAL: PLAINTEXT_INTERNAL
      KAFKA_LISTENER_NAME_EXTERNAL: PLAINTEXT_EXTERNAL
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
    networks:
      - health_monitoring_network
  kafdrop:
    depends_on:
      - kafka
    image: obsidiandynamics/kafdrop:4.1.0
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      SERVER_SERVLET_CONTEXTPATH: /
    networks:
      - health_monitoring_network
  cassandra:
    image: cassandra:5.0.2
    container_name: cassandra
    ports:
      - 9042:9042
    environment:
      CASSANDRA_SEEDS: cassandra
      CASSANDRA_CLUSTER_NAME: HealthMonitoringCluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      CASSANDRA_HOST: cassandra
      CASSANDRA_LISTENER_INTERNAL: cassandra:9042
      CASSANDRA_LISTENER_EXTERNAL: localhost:9042
      CASSANDRA_LISTENER_INTERFACES: INTERNAL,EXTERNAL
      CASSANDRA_AUTO_BOOTSTRAP: false
      CASSANDRA_SKIP_WAIT_FOR_GOSSIP_TO_SETTLE: 1
      CASSANDRA_MIGRATION: false
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - health_monitoring_network
  # prometheus:
  #   depends_on:
  #     health-monitoring-consumer-data:
  #       condition: service_healthy
  #   image: prom/prometheus:v3.2.1
  #   container_name: prometheus
  #   volumes:
  #     - "./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - health_monitoring_network
  # grafana:
  #   depends_on:
  #     - prometheus
  #   image: grafana/grafana:11.5.2
  #   container_name: grafana
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #     - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
  #   volumes:
  #     - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
  #     - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources
  #   networks:
  #     - health_monitoring_network
  iot-devices-simulator:
    build: iot-devices-simulator
    image: iot-devices-simulator:latest
    container_name: iot-devices-simulator
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    networks:
      - health_monitoring_network
  # health-monitoring-producer-data:
  #   depends_on:
  #     - emqx
  #     - kafka
  #   build: health-monitoring-producer-data
  #   image: health-monitoring-producer-data:latest
  #   command: java -Dspring.profiles.active=docker -jar target/health-monitoring-producer-data-0.0.1-SNAPSHOT.jar
  #   container_name: health-monitoring-producer-data
  #   healthcheck:
  #     test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8081/actuator/health"]
  #     interval: 10s
  #     retries: 5
  #     start_period: 10s
  #     timeout: 5s
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - health_monitoring_network
  # health-monitoring-consumer-data:
  #   depends_on:
  #     cassandra:
  #       condition: service_healthy
  #     health-monitoring-producer-data:
  #       condition: service_healthy
  #   build: health-monitoring-consumer-data
  #   image: health-monitoring-consumer-data:latest
  #   command: java -Dspring.profiles.active=docker -jar target/health-monitoring-consumer-data-0.0.1-SNAPSHOT.jar
  #   container_name: health-monitoring-consumer-data
  #   healthcheck:
  #     test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8082/actuator/health"]
  #     interval: 10s
  #     retries: 5
  #     start_period: 10s
  #     timeout: 5s
  #   ports:
  #     - 8082:8082
  #   networks:
  #     - health_monitoring_network
  # health-monitoring-consumer-api:
  #   depends_on:
  #     health-monitoring-consumer-data:
  #       condition: service_healthy
  #   build: health-monitoring-consumer-api
  #   image: health-monitoring-consumer-api:latest
  #   command: java -Dspring.profiles.active=docker -jar target/health-monitoring-consumer-api-0.0.1-SNAPSHOT.jar
  #   container_name: health-monitoring-consumer-api
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - health_monitoring_network
networks:
  health_monitoring_network:
    driver: bridge
