{
 "title": "Consumer Data Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Mensagens Consumidas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "kafka_messages_consumed_total", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Total Mensagens Consumidas Topico: devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_topic_devices_messages_consumed_total",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "DQL - Mensagens com erro de processamento",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_topic_dead_letter_queue_messages_produced_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}