spring.application.name=health-monitoring-producer-data

# Health check configuration
server.port=8081
management.health.status.http-mapping.UP=200
management.health.status.http-mapping.DOWN=503
management.endpoints.web.exposure.include=*
management.endpoint.metrics.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.export.prometheus.step=5s

# Logging configuration (TRACE, DEBUG, INFO, WARN, ERROR, FATAL)
log.level=INFO

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9093
spring.kafka.topics.devices.name=devices
spring.kafka.topics.devices.partitions=1
spring.kafka.topics.devices.replication-factor=1
spring.kafka.topics.register.partitions=8
spring.kafka.topics.register.replication-factor=1

# EMQX Broker configuration
broker.emqx.url=tcp://localhost:1883
broker.emqx.client-id=health-monitoring-producer-data
broker.emqx.timeout=30
broker.emqx.topic=devices/#
