spring.application.name=health-monitoring-broker
server.port=-1
management.server.port=8081
management.endpoints.web.exposure.include=health
management.health.status.http-mapping.UP=200
management.health.status.http-mapping.DOWN=503

# Logging configuration (TRACE, DEBUG, INFO, WARN, ERROR, FATAL)
log.level=INFO

# Kafka configuration
spring.kafka.bootstrap-servers=kafka:9092

# EMQX Broker configuration
broker.emqx.url=tcp://emqx:1883
broker.emqx.client-id=health-monitoring-broker
broker.emqx.timeout=30

# Cassandra configuration
spring.data.cassandra.host=cassandra
spring.data.cassandra.port=9042
spring.data.cassandra.local-datacenter=datacenter1

# IoT Devices Health Monitoring
device.heartbeat=8T4iF,A8pMD,eHrUQ
# device.another_device=ID_1,ID_2,ID_3,[...]
