spring.application.name=health-monitoring-consumer-data

# Health check configuration
server.port=-1
management.server.port=8082
management.endpoints.web.exposure.include=health
management.health.status.http-mapping.UP=200
management.health.status.http-mapping.DOWN=503

# Logging configuration (TRACE, DEBUG, INFO, WARN, ERROR, FATAL)
log.level=INFO

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9093
spring.kafka.consumer.group-id=health-monitoring-consumer-data
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.topics.dlq.name=dead_letter_queue
spring.kafka.topics.dlq.partitions=3
spring.kafka.topics.dlq.replication-factor=1
spring.kafka.topics.execution-retries=3
spring.kafka.topics.interval-retries=2000
spring.kafka.topics.devices.name=devices

# Cassandra configuration
spring.data.cassandra.host=localhost
spring.data.cassandra.port=9042
spring.data.cassandra.local-datacenter=datacenter1
spring.data.cassandra.keyspace-name=health_monitoring
